### ISSUE TITLE
Source strings are always "NINJA-IDE".

### ISSUE THREAD

**Issue by Atalanttore** [ninja-ide/ninja-ide-translations#36]
Hi,

the source strings in [ninja.ts](https://github.com/ninja-ide/ninja-ide-translations/blob/master/ninja.ts) are always "NINJA-IDE". The actual string for translation seems to be in the `comment` tag. Why???

Regards,
Ettore

**Comment by centaurialpha** [comment]
Yes, you are right. I'm going to check it. Thanks!!

**Comment by centaurialpha** [comment]
I have used `QtCore.QCoreApplication.tr` instead of `QtCore.QCoreApplication.translate` and the problem has been solved.

**Comment by Atalanttore** [comment]
The problem still exists in [ninja.ts](https://github.com/ninja-ide/ninja-ide-translations/blob/master/ninja.ts).

**Comment by centaurialpha** [comment]
Yes, I've only solved it locally, as soon as we have a release version the [ninja.ts](https://github.com/ninja-ide/ninja-ide-translations/blob/master/ninja.ts) will be updated.

**Comment by Atalanttore** [comment]
The last release version [v2.3](https://github.com/ninja-ide/ninja-ide/releases) of NINJA-IDE was released in July 2013. How soon is the next release version of NINJA-IDE?

**Comment by centaurialpha** [comment]
In two o three months :)

**Comment by Atalanttore** [comment]
Great! Is it possible to get your local ninja.ts for a new translation?

**Comment by centaurialpha** [comment]
In this week I will update the [ninja.ts](https://github.com/ninja-ide/ninja-ide-translations/blob/master/ninja.ts) I promise! ;)
